// <auto-generated />
using System;
using DataAccessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessObject.Migrations
{
    [DbContext(typeof(MusicProjectContext))]
    partial class MusicProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Model.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Model.Beat", b =>
                {
                    b.Property<int>("BeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeatID"));

                    b.Property<int>("BeatIndex")
                        .HasColumnType("int");

                    b.Property<int>("MeasureID")
                        .HasColumnType("int");

                    b.HasKey("BeatID");

                    b.HasIndex("MeasureID");

                    b.ToTable("Beats");
                });

            modelBuilder.Entity("BusinessObject.Model.Clef", b =>
                {
                    b.Property<int>("ClefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClefID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClefID");

                    b.ToTable("Clefs");
                });

            modelBuilder.Entity("BusinessObject.Model.Instrument", b =>
                {
                    b.Property<int>("InstrumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultSoundID")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("InstrumentID");

                    b.HasIndex("DefaultSoundID")
                        .IsUnique()
                        .HasFilter("[DefaultSoundID] IS NOT NULL");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("BusinessObject.Model.KeySignature", b =>
                {
                    b.Property<int>("KeySignatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeySignatureID"));

                    b.Property<int>("AccidentalCount")
                        .HasColumnType("int");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeySignatureID");

                    b.ToTable("KeySignatures");
                });

            modelBuilder.Entity("BusinessObject.Model.Measure", b =>
                {
                    b.Property<int>("MeasureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasureID"));

                    b.Property<int>("EndBarline")
                        .HasColumnType("int");

                    b.Property<int>("LeftBarline")
                        .HasColumnType("int");

                    b.Property<int>("MeasureNumber")
                        .HasColumnType("int");

                    b.Property<int>("RightBarline")
                        .HasColumnType("int");

                    b.Property<int>("SongID")
                        .HasColumnType("int");

                    b.Property<int?>("TimeSignatureID")
                        .HasColumnType("int");

                    b.HasKey("MeasureID");

                    b.HasIndex("SongID");

                    b.HasIndex("TimeSignatureID");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("BusinessObject.Model.MusicalEvent", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<int>("BaseNoteType")
                        .HasColumnType("int");

                    b.Property<int>("DotCount")
                        .HasColumnType("int");

                    b.Property<float>("DurationInBeats")
                        .HasColumnType("real");

                    b.Property<float>("GraceDurationRatio")
                        .HasColumnType("real");

                    b.Property<bool>("IsChord")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGraceNote")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRest")
                        .HasColumnType("bit");

                    b.Property<int>("MeasureID")
                        .HasColumnType("int");

                    b.Property<float>("StartBeat")
                        .HasColumnType("real");

                    b.Property<int?>("TupletID")
                        .HasColumnType("int");

                    b.HasKey("EventID");

                    b.HasIndex("MeasureID");

                    b.HasIndex("TupletID");

                    b.ToTable("MusicalEvents");
                });

            modelBuilder.Entity("BusinessObject.Model.NotationItem", b =>
                {
                    b.Property<int>("NotationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotationID"));

                    b.Property<int?>("Articulation")
                        .HasColumnType("int");

                    b.Property<int?>("Dynamic")
                        .HasColumnType("int");

                    b.Property<float?>("EndBeat")
                        .HasColumnType("real");

                    b.Property<int?>("HairpinType")
                        .HasColumnType("int");

                    b.Property<bool>("IsCrescendo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiminuendo")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHairpinEnd")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHairpinStart")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLyric")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStaffText")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSustainPedal")
                        .HasColumnType("bit");

                    b.Property<int>("MeasureID")
                        .HasColumnType("int");

                    b.Property<int?>("Ornament")
                        .HasColumnType("int");

                    b.Property<bool>("PedalEnd")
                        .HasColumnType("bit");

                    b.Property<bool>("PedalStart")
                        .HasColumnType("bit");

                    b.Property<float>("StartBeat")
                        .HasColumnType("real");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotationID");

                    b.HasIndex("MeasureID");

                    b.ToTable("NotationItems");
                });

            modelBuilder.Entity("BusinessObject.Model.NotePitch", b =>
                {
                    b.Property<int>("NotePitchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotePitchID"));

                    b.Property<int>("Alter")
                        .HasColumnType("int");

                    b.Property<int?>("Fret")
                        .HasColumnType("int");

                    b.Property<int>("MusicalEventID")
                        .HasColumnType("int");

                    b.Property<int>("Octave")
                        .HasColumnType("int");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.Property<int?>("StringNumber")
                        .HasColumnType("int");

                    b.HasKey("NotePitchID");

                    b.HasIndex("MusicalEventID");

                    b.ToTable("NotePitches");
                });

            modelBuilder.Entity("BusinessObject.Model.NoteType", b =>
                {
                    b.Property<int>("NoteTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteTypeID"));

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("MusicalEventEventID")
                        .HasColumnType("int");

                    b.Property<string>("NoteTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoteTypeID");

                    b.HasIndex("MusicalEventEventID");

                    b.ToTable("NoteTypes");
                });

            modelBuilder.Entity("BusinessObject.Model.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BusinessObject.Model.Rest", b =>
                {
                    b.Property<int>("RestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestID"));

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("MeasureID")
                        .HasColumnType("int");

                    b.Property<float>("StartBeat")
                        .HasColumnType("real");

                    b.HasKey("RestID");

                    b.HasIndex("MeasureID");

                    b.ToTable("Rests");
                });

            modelBuilder.Entity("BusinessObject.Model.Sheet", b =>
                {
                    b.Property<int>("SheetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SheetID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InitialTempoBPM")
                        .HasColumnType("int");

                    b.Property<string>("InitialTempoText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KeySignatureID")
                        .HasColumnType("int");

                    b.Property<int>("SongID")
                        .HasColumnType("int");

                    b.Property<int>("TimeSignatureID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SheetID");

                    b.HasIndex("KeySignatureID");

                    b.HasIndex("SongID");

                    b.HasIndex("TimeSignatureID");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("BusinessObject.Model.Song", b =>
                {
                    b.Property<int>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongID"));

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Composer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SongID");

                    b.HasIndex("AccountID");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("BusinessObject.Model.Sound", b =>
                {
                    b.Property<int>("SoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoundID"));

                    b.Property<int?>("Channels")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultInstrumentID")
                        .HasColumnType("int");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstrumentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProviderUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("int");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("SoundID");

                    b.ToTable("Sounds");
                });

            modelBuilder.Entity("BusinessObject.Model.SoundPack", b =>
                {
                    b.Property<int>("SoundPackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoundPackID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoundPackID");

                    b.ToTable("SoundPacks");
                });

            modelBuilder.Entity("BusinessObject.Model.SoundPackItem", b =>
                {
                    b.Property<int>("SoundPackItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoundPackItemID"));

                    b.Property<int>("SoundID")
                        .HasColumnType("int");

                    b.Property<int>("SoundPackID")
                        .HasColumnType("int");

                    b.HasKey("SoundPackItemID");

                    b.HasIndex("SoundID");

                    b.HasIndex("SoundPackID");

                    b.ToTable("SoundPackItems");
                });

            modelBuilder.Entity("BusinessObject.Model.TimeSignature", b =>
                {
                    b.Property<int>("TimeSignatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSignatureID"));

                    b.Property<int>("BeatUnit")
                        .HasColumnType("int");

                    b.Property<int>("BeatsPerMeasure")
                        .HasColumnType("int");

                    b.HasKey("TimeSignatureID");

                    b.ToTable("TimeSignatures");
                });

            modelBuilder.Entity("BusinessObject.Model.Track", b =>
                {
                    b.Property<int>("TrackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackID"));

                    b.Property<int>("ClefID")
                        .HasColumnType("int");

                    b.Property<int>("ClefType")
                        .HasColumnType("int");

                    b.Property<int?>("InstrumentID")
                        .HasColumnType("int");

                    b.Property<string>("InstrumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTablature")
                        .HasColumnType("bit");

                    b.Property<int>("SheetID")
                        .HasColumnType("int");

                    b.Property<int?>("Transpose")
                        .HasColumnType("int");

                    b.HasKey("TrackID");

                    b.HasIndex("ClefID");

                    b.HasIndex("InstrumentID");

                    b.HasIndex("SheetID");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("BusinessObject.Model.TupletGroup", b =>
                {
                    b.Property<int>("TupletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TupletID"));

                    b.Property<int>("ActualNotes")
                        .HasColumnType("int");

                    b.Property<int>("NormalNotes")
                        .HasColumnType("int");

                    b.HasKey("TupletID");

                    b.ToTable("TupletGroups");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "2",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "3",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "4",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "5",
                            ConcurrencyStamp = "5",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Model.Beat", b =>
                {
                    b.HasOne("BusinessObject.Model.Measure", "Measure")
                        .WithMany("Beats")
                        .HasForeignKey("MeasureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measure");
                });

            modelBuilder.Entity("BusinessObject.Model.Instrument", b =>
                {
                    b.HasOne("BusinessObject.Model.Sound", "DefaultSound")
                        .WithOne("DefaultInstrument")
                        .HasForeignKey("BusinessObject.Model.Instrument", "DefaultSoundID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultSound");
                });

            modelBuilder.Entity("BusinessObject.Model.Measure", b =>
                {
                    b.HasOne("BusinessObject.Model.Song", "Song")
                        .WithMany("Measures")
                        .HasForeignKey("SongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.TimeSignature", "TimeSignature")
                        .WithMany()
                        .HasForeignKey("TimeSignatureID");

                    b.Navigation("Song");

                    b.Navigation("TimeSignature");
                });

            modelBuilder.Entity("BusinessObject.Model.MusicalEvent", b =>
                {
                    b.HasOne("BusinessObject.Model.Measure", "Measure")
                        .WithMany("Notes")
                        .HasForeignKey("MeasureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.TupletGroup", "Tuplet")
                        .WithMany()
                        .HasForeignKey("TupletID");

                    b.Navigation("Measure");

                    b.Navigation("Tuplet");
                });

            modelBuilder.Entity("BusinessObject.Model.NotationItem", b =>
                {
                    b.HasOne("BusinessObject.Model.Measure", "Measure")
                        .WithMany("Notations")
                        .HasForeignKey("MeasureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measure");
                });

            modelBuilder.Entity("BusinessObject.Model.NotePitch", b =>
                {
                    b.HasOne("BusinessObject.Model.MusicalEvent", "MusicalEvent")
                        .WithMany("Pitches")
                        .HasForeignKey("MusicalEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicalEvent");
                });

            modelBuilder.Entity("BusinessObject.Model.NoteType", b =>
                {
                    b.HasOne("BusinessObject.Model.MusicalEvent", "MusicalEvent")
                        .WithMany("NoteTypes")
                        .HasForeignKey("MusicalEventEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicalEvent");
                });

            modelBuilder.Entity("BusinessObject.Model.RefreshToken", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Model.Rest", b =>
                {
                    b.HasOne("BusinessObject.Model.Measure", "Measure")
                        .WithMany("Rests")
                        .HasForeignKey("MeasureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measure");
                });

            modelBuilder.Entity("BusinessObject.Model.Sheet", b =>
                {
                    b.HasOne("BusinessObject.Model.KeySignature", "KeySignature")
                        .WithMany("Sheets")
                        .HasForeignKey("KeySignatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.Song", "Song")
                        .WithMany("Sheets")
                        .HasForeignKey("SongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.TimeSignature", "TimeSignature")
                        .WithMany("Sheets")
                        .HasForeignKey("TimeSignatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeySignature");

                    b.Navigation("Song");

                    b.Navigation("TimeSignature");
                });

            modelBuilder.Entity("BusinessObject.Model.Song", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", "Account")
                        .WithMany("Songs")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Model.SoundPackItem", b =>
                {
                    b.HasOne("BusinessObject.Model.Sound", "Sound")
                        .WithMany("SoundPackItems")
                        .HasForeignKey("SoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.SoundPack", "SoundPack")
                        .WithMany("Items")
                        .HasForeignKey("SoundPackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sound");

                    b.Navigation("SoundPack");
                });

            modelBuilder.Entity("BusinessObject.Model.Track", b =>
                {
                    b.HasOne("BusinessObject.Model.Clef", "Clef")
                        .WithMany("Tracks")
                        .HasForeignKey("ClefID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.Instrument", null)
                        .WithMany("Tracks")
                        .HasForeignKey("InstrumentID");

                    b.HasOne("BusinessObject.Model.Sheet", "Sheet")
                        .WithMany("Tracks")
                        .HasForeignKey("SheetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clef");

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObject.Model.Account", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("BusinessObject.Model.Clef", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("BusinessObject.Model.Instrument", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("BusinessObject.Model.KeySignature", b =>
                {
                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("BusinessObject.Model.Measure", b =>
                {
                    b.Navigation("Beats");

                    b.Navigation("Notations");

                    b.Navigation("Notes");

                    b.Navigation("Rests");
                });

            modelBuilder.Entity("BusinessObject.Model.MusicalEvent", b =>
                {
                    b.Navigation("NoteTypes");

                    b.Navigation("Pitches");
                });

            modelBuilder.Entity("BusinessObject.Model.Sheet", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("BusinessObject.Model.Song", b =>
                {
                    b.Navigation("Measures");

                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("BusinessObject.Model.Sound", b =>
                {
                    b.Navigation("DefaultInstrument");

                    b.Navigation("SoundPackItems");
                });

            modelBuilder.Entity("BusinessObject.Model.SoundPack", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BusinessObject.Model.TimeSignature", b =>
                {
                    b.Navigation("Sheets");
                });
#pragma warning restore 612, 618
        }
    }
}
